### ISSUE TITLE
1.3.1版本，配置之后，点击＋号无法自动打开网页

### ISSUE THREAD

**Issue by slZheng077** [cs-lazy-tools/ChatGPT-On-CS#45]
我使用的1.3.1版本软件，按照使用说明书中点击➕，是添加一个客服的功能，无法打开网页应用

**Comment by gaoming714** [comment]
同样的问题，微信（桌面应用）可以使用，但是抖音和抖店抖没有打开web页面。

**Comment by gaoming714** [comment]
下面是报的错误，我有两个疑问，是不是需要安装webdriver？另一问题，这里提到的文件我没找到，文档里说，复制backend里的懒人百宝箱我也没有找到在哪里。愿闻其详。
`

stdout: 2024-08-13 21:28:13.082 | INFO     | ====== WebDriver manager ======
stdout: 2024-08-13 21:28:56.957 | INFO     | StrategyService handlers registered.
stdout: 2024-08-13 21:28:56.965 | INFO     | Connection established with the server.
2024-08-13 21:28:56.965 | INFO     | Successfully connected to the server.
2024-08-13 21:28:56.965 | INFO     | Connected to server: http://127.0.0.1:54056
stdout: 2024-08-13 21:29:04.946 | WARNING  |           ....
stdout: 2024-08-13 21:29:04.946 | INFO     | ====== WebDriver manager ======
stdout: 2024-08-13 21:29:17.475 | ERROR    |      쳣: OSError: [WinError 193] %1       Ч   Win32 Ӧ ó    
  쳣  ջ: Traceback (most recent call last):
  File "D:\Portable\chatgpt-on-cs\resources\assets\backend\app\core\asyncselenium\web_bot.py", line 78, in async_wrapper
  File "D:\Portable\chatgpt-on-cs\resources\assets\backend\app\core\asyncselenium\web_bot.py", line 1585, in execute_script
  File "D:\Portable\chatgpt-on-cs\resources\assets\backend\app\core\asyncselenium\web_bot.py", line 1780, in __get_driver
  File "D:\Portable\chatgpt-on-cs\resources\assets\backend\app\core\asyncselenium\web_driver_config.py", line 79, in init_driver
  File "D:\Portable\chatgpt-on-cs\resources\assets\backend\app\core\asyncselenium\webdriver\remote\async_object.py", line 4, in __new__
  File "D:\Portable\chatgpt-on-cs\resources\assets\backend\app\core\asyncselenium\webdriver\chrome\async_webdriver.py", line 37, in __init__
  File "D:\Portable\chatgpt-on-cs\resources\assets\backend\selenium\webdriver\common\service.py", line 98, in start
  File "D:\Portable\chatgpt-on-cs\resources\assets\backend\selenium\webdriver\common\service.py", line 208, in _start_process
  File "D:\Portable\chatgpt-on-cs\resources\assets\backend\subprocess.py", line 1026, in __init__
  File "D:\Portable\chatgpt-on-cs\resources\assets\backend\subprocess.py", line 1538, in _execute_child
OSError: [WinError 193] %1       Ч   Win32 Ӧ ó   

2024-08-13 21:29:17.475 | WARNING  |           ....
stdout: 2024-08-13 21:29:17.475 | INFO     | ====== WebDriver manager ======


`

**Comment by lrhh123** [comment]
已修复
